name: Add Releases

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Archive FR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-fr
        path: |
          .
          !*fr*
  
    - name: Release Test
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release-fr.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
