name: Add Releases

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Archive FR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-fr
        path: |
          .
          !*fr*
  
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        release_name: release separate
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload fr artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-fr.zip
