name: Add Releases

on: push

jobs:
  draft:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create Draft Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        release_name: draft-split-rel
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    outputs:
      release-upload-url: ${{ steps.create_release.outputs.upload_url }}

  build:
    runs-on: ubuntu-latest
    needs: draft
    strategy:
      matrix:
        lang: ['fr', 'es-la', 'pt-br', 'en']
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add Commit Author
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
    
    - name: Create Separate Branch for ${{ matrix.lang }}
      run: |
        git rm -r doc -- ':!*${{ matrix.lang }}*'
        git rm -r mupl/loc -- ':!*${{ matrix.lang }}*'
        git switch -c ${{ matrix.lang }}-release
        git commit -m '${{ matrix.lang }} release'
        git switch -
    
    - name: Archive Branch
      run: git archive --format=zip --output ./release-${{ matrix.lang }}.zip ${{ matrix.lang }}-release
  
    - name: upload ${{ matrix.lang }} artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.draft.outputs.release-upload-url }}
        asset_path: ./release-${{ matrix.lang }}.zip
        asset_name: release-${{ matrix.lang }}.zip
        asset_content_type: application/zip
