name: Add Releases

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add Commit Author
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions"
    
    - name: Create Separate Branch
      run: |
        git rm -r doc -- ':!*fr*'
        git rm -r mupl/loc -- ':!*fr*'
        git switch -c fr-release
        git commit -m 'fr release'
        git switch -
    
    - name: Archive Branch
      run: git archive --format=zip --output ./release-fr.zip fr-release
  
    - name: Create Draft Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        release_name: draft-rel
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload fr artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-fr.zip
        asset_name: release-fr.zip
        asset_content_type: application/zip
